version: '3'

services:
  eurostreaming_scraping:
    image: matt0550/eurostreamingapi-scraping
    environment:
      - PUID=1000     # UID of the user inside the container
      - PGID=1000     # GID of the user inside the container
    ports:
      - 7013:5000
    restart: unless-stopped